build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

site_name: Kiwi Docs
nav:
  - Home: index.md
  - Carbon Scopes: scopes.md
  - L/T Split: lt.md
  - DQ: dq.md
  - Portfolio & Dashboards: ui.md
theme:
  name: readthedocs
