# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

mkdocs:
  configuration: mkdocs.yml
site_name: Kiwi Docs
nav:
  - Home: index.md
  - Carbon Scopes: scopes.md
  - L/T Split: lt.md
  - DQ: dq.md
  - Portfolio & Dashboards: ui.md
theme:
  name: readthedocs
