# Required
version: 2

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.7"

mkdocs:
  configuration: mkdocs.yml

