site_name: Kiwi Docs

theme:
  name: material
  logo: img/favicon.ico
  palette:
     # Palette toggle for light mode
    - scheme: default
      primary: light green
      accent: red 
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: light green
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  
nav:
  - Home: index.md
  - Carbon Scopes: scopes.md
  - L/T Split: lt.md
  - DQ: dq.md
  - Portfolio & Dashboards: ui.md
